preserve_hierarchy: true
files:
  - source: /osu.Game.Resources/Localisation/**/*.resx
    translation: /osu.Game.Resources/Localisation/**/%file_name%.%locale%.%file_extension%
    ignore:
      # note that this should probably be using %locale% rather than a simple wildcard
      # but it doesn't seem to respect our mapping below.
      - /osu.Game.Resources/Localisation/**/%file_name%.*.%file_extension%
      # automatically pulled from Crowdin
      - /osu.Game.Resources/Localisation/Web/**/*
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        ar: ar
        be: be
        bg: bg
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        es-ES: es
        fi: fi
        fil: fil
        fr: fr
        he: he
        hu: hu
        id: id
        it: it
        ja: ja
        ko: ko
        lt: lt
        nl: nl
        'no': 'no'
        pl: pl
        pt-BR: pt-BR
        pt-PT: pt
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sr: sr
        sv-SE: sv
        th: th
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh
        zh-TW: zh-Hant
