name: Pack and nuget

on:
  push:
    tags:
      - '*'

jobs:
  notify_pending_production_deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Submit pending deployment notification
        run: |
          export TITLE="Pending osu-resources Production Deployment: $GITHUB_REF_NAME"
          export URL="https://github.com/ppy/osu-resources/actions/runs/$GITHUB_RUN_ID"
          export DESCRIPTION="Awaiting approval for building NuGet packages for tag $GITHUB_REF_NAME:
          [View Workflow Run]($URL)"
          export ACTOR_ICON="https://avatars.githubusercontent.com/u/$GITHUB_ACTOR_ID"

          BODY="$(jq --null-input '{
            "embeds": [
              {
                "title": env.TITLE,
                "color": 15098112,
                "description": env.DESCRIPTION,
                "url": env.URL,
                "author": {
                  "name": env.GITHUB_ACTOR,
                  "icon_url": env.ACTOR_ICON
                }
              }
            ]
          }')"

          curl \
            -H "Content-Type: application/json" \
            -d "$BODY" \
            "${{ secrets.DISCORD_INFRA_WEBHOOK_URL }}"

  pack:
    name: Pack
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set artifacts directory
        id: artifactsPath
        run: echo "::set-output name=nuget_artifacts::${{github.workspace}}/artifacts"

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Pack
        run: dotnet pack -c Release osu.Game.Resources /p:Version=${{ github.ref_name }} /p:GenerateDocumentationFile=true /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg -o ${{steps.artifactsPath.outputs.nuget_artifacts}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: osu-resources
          path: |
            ${{steps.artifactsPath.outputs.nuget_artifacts}}/*.nupkg
            ${{steps.artifactsPath.outputs.nuget_artifacts}}/*.snupkg

      - name: Publish packages to nuget.org
        run: dotnet nuget push ${{steps.artifactsPath.outputs.nuget_artifacts}}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json